version: '3'

services:
  flask:
    container_name: shark-container
    image: capstone-image
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
