version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    expose:
      - "5000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
